web:
  build: .
  dockerfile: Dockerfile-development
  links:
   - db
  ports:
   - "8000:8000"
  volumes:
   - .:/usr/src/app/
  environment:
   NODE_ENV: development 
   MONGO_URL: mongodb://velingkar:margao@ds161162.mlab.com:61162/raven-planner
db:
  image: mongo:latest
  ports:
   - "27017:27017"

